import Head from 'next/head'

import RangeSlider from '../components/RangeSlider'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <RangeSlider/>
      </main>

     
    </div>
  )
}
