import Head from 'next/head'

import RangeSlider from '../components/RangeSlider'


export default function Home() {
  return (
    <div >
      <Head>
        <title>RangeSlider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className='bg-black rounded flex justify-center items-center'>
          <h1 className='text-red-700 font-extrabold '>Range Slider</h1>
        </div>
      </main>

     
    </div>
  )
}
